### ISSUE TITLE
display Error: ENOENT: no such file or directory ,it s not a bug

### ISSUE THREAD

**Issue by babakjahan** [CodeYourFuture/Class-Planner#63]
Error appear when run backend 
Error: ENOENT: no such file or directory, stat '/Users/babak/Projects/CYF/Final Project/Class-Planner/frontend/build/index.html' 

Server.js line 22 , wrong path 

this setting should be for Heroku , but is it possible solve it in dev ?

if netlify.toml is work, is it necessary we keep this line ( server.js Line 22) ?

**Comment by byohannes** [comment]
backend is running normally
I do not know how did you get that error
have you tried: npm run server
