### ISSUE TITLE
Cancel button doesn't work on upcoming class 

### ISSUE THREAD

**Issue by babakjahan** [CodeYourFuture/Class-Planner#66]
As an admin when I go to the upcoming class page [(https://cyf-class-planner.herokuapp.com/upcomingclass/)](https://cyf-class-planner.herokuapp.com/upcomingclass/)  , and when cancel button clicked then it only shows the loading .

**Comment by byohannes** [comment]
That is right as the upcoming class only shows one class so @AKaramifar is updating the screen of the upcoming class component then it will work and thanks
