### ISSUE TITLE
home page for mobile device view, the title Class planner is hidden 

### ISSUE THREAD

**Issue by byohannes** [CodeYourFuture/Class-Planner#67]
![desktop](https://user-images.githubusercontent.com/42332389/92926345-c7c04f00-f433-11ea-9b3c-7c7bea4a6dc9.png)
![mobile](https://user-images.githubusercontent.com/42332389/92926350-cabb3f80-f433-11ea-95b6-ce75b8df981e.png)

**Comment by babakjahan** [comment]
has fixed
