### ISSUE TITLE
Multiple attend forms appear on cousercalander

### ISSUE THREAD

**Issue by babakjahan** [CodeYourFuture/Class-Planner#69]
JFYI : 
When user browse http://localhost:3000/coursecalendar/ and click on attend then click on browser back button and back to  the course calendar page , multiple attend forms appear below of each ClassCard . 

I dont know its bug or what but anyway I've reported as issue here.

**Comment by byohannes** [comment]
This feature has been updated and fixed, and @AKaramifar has fixed it.
